
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://chris-shum.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Chris Shum"
title: "{ Chris Shum }"
description: "Digital Resume of Chris Shum"
keywords: "shum, chris, android, personal, jekyll, theme"
favicon: "/img/android.ico"

################
# Header layout #
################

black-favicon: "/img/androidheader.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Digital resume of Chris Shum"
  - text: "Welcome!"

me-img: "/img/androidself.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 30

paginate: 10

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ga.png"
    date: "2016-Present"
    description: "Android Development Instructional Associate"
  - image: "/img/timeline/udacity.png"
    date: "In Progress"
    description: "Android Developer Nanodegree"
  - image: "/img/timeline/intense.png"
    date: "2014-2015"
    description: "Electro-Mechanical Engineer"
  - image: "/img/timeline/mmu.png"
    date: "2014"
    description: "Masters in Mechanical Engineering"
  - image: "/img/timeline/rutgers.png"
    date: "2012"
    description: "Bachelors in Physics"
  - image: "/img/timeline/trumpf.png"
    date: "2009-2012"
    description: "Lead Technician"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "shum.chris8@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Chris Shum is an aspiring Android developer.  Currently open to all opportunities available."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/chris-shum"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/shumchris"
  - title: "instagram"
    url: "https://instagram.com/chrisshowme"
  - title: "twitter"
    url: "https://twitter.com/chrisshowme1"



############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username:
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Summary: 'about'
  Timeline: 'timeline'
  About: 'latest-post'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
